### ISSUE TITLE
the problem with installing 'authomatic' into environment.

### ISSUE THREAD

**Issue by bubanoid** [peterhudec/authomatic#101]
doing the 
virtualenv env && . env/bin/activate && pip install -r requirements.txt
where requirements.txt contains the line
-e git+git@github.com:peterhudec/authomatic.git@a3058fac78827d66f4d3a2e4e5739ee95cff0261#egg=Authomatic-master

I've derived the following error:

Cloning git@github.com:peterhudec/authomatic.git (to a3058fac78827d66f4d3a2e4e5739ee95cff0261) to ./env/src/authomatic-master
Could not find a tag or branch 'a3058fac78827d66f4d3a2e4e5739ee95cff0261', assuming commit.

The similar problem with another package was reported here:
https://github.com/edx/XBlock/issues/164
So, I suppose that the problem is caused by the conflict of Authomatic with another package already installed into my system. 

How to resolve this problem?

**Comment by peterhudec** [comment]
I was not able to reproduce your problem. All of the following commands work on my machine:

```bash
$ pip install -e git+git@github.com:peterhudec/authomatic.git@a30#egg=Authomatic-master
$ pip install -e git+git@github.com:peterhudec/authomatic.git@a3058fa#egg=Authomatic-master
$ pip install -e $ git+git@github.com:peterhudec/authomatic.git@a3058fac78827d66f4d3a2e4e5739ee95cff0261#egg=Authomatic-master

$ pip install -e git+https://github.com/peterhudec/authomatic.git@a3058fa#egg=Authomatic-master
```
All of them also work with `pip install -r requirements.txt`.

The **Could not find a tag or branch 'a3058fa', assuming commit.** message is actually not an error but just an information that git could not find a branch or tag named `a3058fa` so it assumes it is a revision hash.

Could you please provide the full output of the install command?

**Comment by bubanoid** [comment]
Hello. I could not reproduce my problem again. The only thing I remember is that the problem was solved by the command 
pip install -U setuptools
