### ISSUE TITLE
ImportError: No module named 'authomatic'

### ISSUE THREAD

**Issue by pinkeshdarji** [peterhudec/authomatic#146]
![noauthomatic](https://cloud.githubusercontent.com/assets/14161219/14982703/d878f90c-1155-11e6-8556-914a276a5c77.png)
I am trying to run pyramid example from 
D:\pinkesh2\PythonProjects\authomatic-master\examples\pyramid\simple
I have also done pip install authomatic.
While trying to run main.py I get 
ImportError: No module named 'authomatic'
Please show me step to run basic pyramid project from start.
Do I am missing something? please help

**Comment by ah3243** [comment]
was this solved i have a similar error
