### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by ambasta** [peterhudec/authomatic#50]
Hi,

Does authomatic have python 3 support? Currently, I am getting a 
---> 21 from core import Authomatic, setup, login, provider_id, access, async_access, credentials, request_elements, backend

ImportError: No module named 'core'

**Comment by touilleMan** [comment]
@bradjc Your fix seems pretty nice, I've merged it into my fork
@peterhudec It could be interesting to merge my fork into a new py3k branch in your repository, this way it would be easier to keep this branch up to date with the master and let people contribute to it while beeing able to test it extensively.

Given the branch is python2/3 compatible, I have in mind we could use it as master once stable enough, what do you think ?

**Comment by peterhudec** [comment]
Yes, that's a good idea. I have just created the branch.

@touilleMan, @bradjc, I cannot describe by words how I appreciate your contributions. Unfortunately, due to family reasons I'm unable to dedicate as much of my time to my projects as I wanted to, so please be patient, when things take a little bit longer on my side.

**Comment by jmagnusson** [comment]
Hope everything is okay with you and your family @peterhudec.

What is needed to get this project to support Python 3 natively? This is the only project keeping me from dumping Python 2 for good!

**Comment by AnderUstarroz** [comment]
You can use the @touilleMan's [Authomatic version for Python 3](https://github.com/touilleMan/authomatic).  I've tried it with a pyramid project in Python 3 and works fine.

**Comment by touilleMan** [comment]
@jmagnusson: I use my branch with python3 on a flask project with github, google and facebook as providers, from my experience at least this part is working great ;-)

**Comment by jmagnusson** [comment]
Thanks guys! Works just fine for me with Googles service.

**Comment by martin-sucha** [comment]
@touilleMan @bradjc I'm testing this with python3 and it seems to work great!
@peterhudec +1 for merging @touilleMan's branch into py3k branch. I see the py3k branch in your repo, but it seems that you forgot to merge the changes?

Thanks everyone!

**Comment by AnderUstarroz** [comment]
Thanks @touilleMan! Based on your branch, I've created an [Authomatic asynchronous version](https://github.com/AnderUstarroz/authomatic) for [aiopyramid](http://aiopyramid.readthedocs.org) (Pyramid + Asyncio).

**Comment by peterhudec** [comment]
@touilleMan's branch is now merged in master. It will take a few days before it is ready to be released.

Thanks @touilleMan et al!

**Comment by peterhudec** [comment]
I have just released Authomatic 0.0.11 with Python 3 support.

Thanks again to everyone!
