### ISSUE TITLE
logging binary 'body' breaks `_fetch`

### ISSUE THREAD

**Issue by eads** [peterhudec/authomatic#86]
I have an app that's creating a spreadsheet on google drive by uploading binary XLSX data, using automatic.access to do it. It would and does work great except that this line in `providers/__init__.py` breaks on binary body data with a UnicodeDecodeError:

```
        self._log(logging.DEBUG, ' \u251C\u2500 body: {0}'.format(body))
```

Working on a patch / workaround but thought I'd let you know.

**Comment by eads** [comment]
An update: This happens with the current pip installable version, but appears to work in the git version.

**Comment by peterhudec** [comment]
@eads, which version do you have installed? Did you try with the most recent `0.0.12` version?

**Comment by eads** [comment]
I think it's safe to say this is fixed. It was happening with 0.0.10 and 0.0.11, but isn't happening with 0.0.12 or bleeding edge git version. Closing.
