### ISSUE TITLE
Twitter location data handling

### ISSUE THREAD

**Issue by iJebus** [peterhudec/authomatic#89]
Something I ran into testing the Flask example and logging in via Twitter. If you're like me, and only had your city in the location field (i.e., Perth, instead of Perth, Australia), this would cause Authomatic to bomb out the login with the error below originating from line 659 of oauth1.py.

_city, _country = _location.split(',')
ValueError: need more than 1 value to unpack

**Comment by g4b1nagy** [comment]
Can confirm that the diff above fixes the issue :)
