### ISSUE TITLE
unicode error with logger & Python 2.7.6

### ISSUE THREAD

**Issue by mleyden** [peterhudec/authomatic#93]
Error with unicode data present in provider and the line 752 /providers/__init__.py:

self._log(logging.INFO, 'Got response. HTTP status = {0}. {1}'.format(response.status, response.content))

Fix is:
self._log(logging.INFO, u'Got response. HTTP status = {0}. {1}'.format(response.status, response.content))

**Comment by peterhudec** [comment]
There is already a pull request open to solve this problem #91

**Comment by pawl** [comment]
This looks like a better fix than the one mentioned in #91, it fixes the problem rather than removing logging content altogether.
