### ISSUE TITLE
Github email seems to be blank

### ISSUE THREAD

**Issue by abridgett** [peterhudec/authomatic#94]
This link seems so suggest that github has a different location for email address:
https://github.com/thephpleague/oauth2-client/issues/9

**Comment by abridgett** [comment]
I should add that this was with scope set to 'user:email' as in github settings you can hide your email addresss from public view (and I really need it for my app so I'm specifically requesting it in the scope.  PS: authomatic is _awesome_ :-)

**Comment by peterhudec** [comment]
I have tested it and always got the email whether with, or without the `'user:email'` scope.

**Comment by abridgett** [comment]
Thanks Peter, I probably wasn't clear enough in my original report (and wanted to double check).

It you visit your https://github.com/settings/profile and set Public Email to "Don't show my email address" then the email address isn't returned.  I appreciate that this is expected if the user:email scope isn't set, however with it it'd be fantastic if authomatic could work it's magic (as the consistent object that it returns is a big help).

**Comment by peterhudec** [comment]
@abridgett Authomatic is a mere consumer of APIs and I can not imagine such magic that would allow a third-party library to force GitHub to expose something in their API which they don't want to expose.

**Comment by abridgett** [comment]
I can't be explaining clearly - I'm certainly not expecting authomatic to somehow magically work around permissions :-) If the user:email scope was set then github's API (according to their docs) does return the email address (whether or not you've asked for it to be kept private).  The privacy setting is respected for the default scope, user:email is that extra permission request which the user will be asked to approve (but may not) that would return the email address.   I could perhaps do this in an additional request outside authomatic, it just seems a shame as it'd be a useful addition.
